# Generated by Django 3.0 on 2021-11-06 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('identity_number', models.IntegerField(blank=True, db_column='Identity number', null=True, unique=True)),
                ('unique_number', models.AutoField(db_column='Unique number', primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_column='Full name', max_length=25)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=10, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=50, null=True)),
                ('discharge_date', models.DateField(blank=True, db_column='Discharge date', null=True)),
                ('delivered_from', models.CharField(blank=True, db_column='Delivered from', max_length=50, null=True)),
                ('admission_date', models.DateField(db_column='Admission date')),
                ('commorbidities', models.CharField(blank=True, db_column='Commorbidities', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('pcr_test', models.CharField(blank=True, db_column='PCR test', max_length=10, primary_key=True, serialize=False)),
                ('quick_test', models.CharField(blank=True, db_column='Quick test', max_length=10, null=True)),
                ('spo2', models.IntegerField(blank=True, db_column='SPO2', null=True)),
                ('respiratory', models.CharField(blank=True, db_column='Respiratory', max_length=50, null=True)),
                ('warning', models.CharField(blank=True, db_column='Warning', max_length=10, null=True)),
                ('ct_value', models.IntegerField(blank=True, db_column='CT value', null=True)),
            ],
            options={
                'db_table': 'Tests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(blank=True, db_column='Symptom', max_length=50, null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'db_table': 'Track',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Treat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_column='Start date')),
                ('end_date', models.DateField(blank=True, db_column='End date', null=True)),
                ('result', models.CharField(blank=True, db_column='Result', max_length=50, null=True)),
                ('patient_number', models.ForeignKey(db_column='Patient number', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Patient')),
            ],
        ),
    ]
